<a href="https://colab.research.google.com/github/gocleanwater/AI-class/blob/main/diabetesClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# diabetes의 Classification
# 왜 분류인가? -> 예측하려는 값 y가 연속적인 숫자가 아닌 이산적이게 나뉜 label이기 때문이다.
# 입력값에 따라 Outcome이 1인지 0인지(당뇨인지 아닌지)를 추측하는 것이기 때문이다.
# 그리고, 이런 건 지도학습이다. 정답 y가 있기 때문에! (모델이 입력 X와 정답 y를 같이 보면서 학습하므로!)

In [6]:
import pandas as pd
import numpy as np

In [7]:
path = '/content/drive/MyDrive/Colab Notebooks/AI-class/diabetes.csv'

df = pd.read_csv(path) #df는 data frame의 준말임

# print(df.head())
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [8]:
y=df['Outcome']
print(y.value_counts())
'''
y.value_counts()는 굳이 왜 할까??
Outcome
0    500
1    268
라는 결과가 나온다.
한쪽 클래스가 너무 많은지 확인하는 용도이다. (너무 0이거나 1이거나 확인하는 것!)
왜? 데이터가 한쪽으로 치우쳐 있으면 모델이 학습하기 어렵기 때문에
왜? 만약 한쪽으로 너무 치우쳐 있으면?
예를 들어 100개 중 95개가 0, 5개가 1이면,
모델이 아 몰라 0으로 찍자 해서 모든 예측값을 0으로 해도, 정확도 95% 가 나올 수 있기 때문!(왜? 95%가 0이니까..)
그래서, 이런 치우쳐진 데이터가 있을 때는 Accuracy를 믿지 못하게 된다.

정리하면, (1) 클래스(label) 개수 확인, (2) 불균형 확인, (3) accuracy 착시 방지, (4) stratify 필요 여부 판단(불균형이 심할 때 파리미터로 사용)
'''
y

Outcome
0    500
1    268
Name: count, dtype: int64

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [9]:
X=df.drop('Outcome',axis=1)
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)
# test_size는 전체 데이터 중 테스트 데이터의 비율(현재 0.25 => 25%가 test)
# random_state는 **데이터를 섞고** 나누는 **랜덤성을 제어**한다고 함. 아무 정수나 상관 없다고 한다.
# 왜 랜덤하게 섞을까?
# 앞쪽 500행이 Outcome = 0, 뒤쪽 268행이 Outcome = 1이면 train에는 0이 너무 많고, test에는 1이 너무 많아
# 학습에 큰 문제가 생길 수도 있기 때문에
# 그럼 왜 랜덤성을 제어하냐? 매번 랜덤하게 섞이면.. 매번 결과가 바뀌면 비교가 어렵다. 그래서, 하나의 임의의 정수로
# 빡 박아놓고 이 정수가 변하지만 않으면 같은 방식으로 랜덤하게 섞이도록 함!

In [11]:
# Logistic Regression 방식
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

clf_lr = LogisticRegression(random_state=0)
# 모델을 하나 만듦(아직 학습 전)
clf_lr.fit(X_train, y_train)
#모델을 학습

'''
LogisticRegression을 classifier라고 설명함.
왜 이름이 Regression(회귀)인데 classifier일까?
로지스틱 회귀는 내부적으로 확률을 예측한다고 함.

예를 들어:
- 당뇨일 확률 0.82 → 1로 분류
- 당뇨일 확률 0.17 → 0으로 분류

즉, 확률을 계산한 뒤, 최종적으로는 클래스를 선택하므로 분류하기 때문에 classifier(분류 모델)이다.
'''

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))
'''
왜 Classification은 성능 지표로 Accuracy를 쓸까?
정확도 = "전체 예측 중 맞춘 비율"이고 수식으로 나타내면, (맞춘 개수)/(전체 개수)이다.
이진 분류(?)에서는 Accuracy = (TP + TN) / (TP + TN + FP + FN)이다.
- TP: 실제 1, 예측 1
- TN: 실제 0, 예측 0
- FP: 실제 0, 예측 1
- FN: 실제 1, 예측 0
라고 한다.

confusion matrix는 아까 TP, TN, FP, FN을 행렬로 보여주는 것이다.
[[TN FP]
 [FN TP]]이다.
'''

--- Logistic Regression Classifier ---
0.796875
[[116  14]
 [ 25  37]]

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

'\n왜 Classification은 성능 지표로 Accuracy를 쓸까?\n정확도 = "전체 예측 중 맞춘 비율"이고 수식으로 나타내면, (맞춘 개수)/(전체 개수)이다.\n이진 분류(?)에서는 Accuracy = (TP + TN) / (TP + TN + FP + FN)이다.\n- TP: 실제 1, 예측 1\n- TN: 실제 0, 예측 0\n- FP: 실제 0, 예측 1\n- FN: 실제 1, 예측 0\n라고 한다.\n\nconfusion matrix는 아까 TP, TN, FP, FN을 행렬로 보여주는 것이다.\n[[TN FP]\n [FN TP]]이다.\n'

In [12]:
# Decision Tree 방식
from sklearn.tree import DecisionTreeClassifier # 여기 부분이 다르다!!
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print("\n--- Decision Tree Classifier ---")
print(accuracy_score(y_test, pred_dt))
print(confusion_matrix(y_test, pred_dt))

--- Decision Tree Classifier ---
0.71875
[[102  28]
 [ 26  36]]

In [13]:
# Random Forest 방식
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

clf_rf = RandomForestClassifier(random_state=0)
clf_rf.fit(X_train, y_train)

pred_rf = clf_rf.predict(X_test)

print("\n--- Random Forest Classifier ---")
print(accuracy_score(y_test, pred_rf))
print(confusion_matrix(y_test, pred_rf))

--- Random Forest Classifier ---
0.7708333333333334
[[116  14]
 [ 30  32]]

Classification에서 LR, DT, RF의 차이 (Logistic Regression, Decision Tree, Random Forest)

https://chatgpt.com/share/69b782ec-15b8-800f-8682-f4faa161a0df